.\"                                      Hey, EMACS: -*- nroff -*-
.TH CONFIG11 1 "February 19, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
config11 \- calculate the floating address space layout of a PDP-11 or VAX
.SH SYNOPSIS
.B config11
.SH DESCRIPTION
This manual page documents briefly the
.B config11
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
Instead, it has documentation in various text files;  see below.
.PP
.SH OPTIONS
For a complete description, see the text file.
.SH SEE ALSO
The program is documented fully by
.PP
.IR /usr/share/doc/simh/config11.txt
.PP
.SH AUTHOR
This manual page was written by Vince Mulhollon <vlm@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
