.\"                                      Hey, EMACS: -*- nroff -*-
.TH I1620 1 "April 14, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
i1620 \- simulate an IBM 1620 computer
.SH SYNOPSIS
.B i1620
.SH DESCRIPTION
This manual page documents briefly the
.B i1620
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
Instead, it has documentation in various text files;  see below.
.PP
.SH OPTIONS
For a complete description, see the text files.
.SH SEE ALSO
The programs are documented fully by
.PP
.IR /usr/share/doc/simh/simh_doc.pdf
.PP
.IR /usr/share/doc/simh/simh_faq.pdf
.PP
.IR /usr/share/doc/simh/simh_breakpoints.pdf
.PP
.IR /usr/share/doc/simh/i1620_doc.pdf
.PP
.IR /usr/share/doc/simh/simh_magtape.pdf
.PP
.IR /usr/share/doc/simh/simh_swre.pdf
.PP
All documentation files are registered with the doc-base system.
.SH AUTHOR
This manual page was written by Vince Mulhollon <vlm@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
