.\"                                      Hey, EMACS: -*- nroff -*-
.TH MMDIR 1 "February 25, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mmdir \- dumps the directory of a simulated Interdata MDM tape
.SH SYNOPSIS
.B mmdir
.SH DESCRIPTION
This manual page documents briefly the
.B mmdir
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
This program dumps the directory of a simulated Interdata MDM tape
.PP
Usage: mmdir filename
.PP
.SH AUTHOR
This manual page was written by Vince Mulhollon <vlm@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
